trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrurl: '$(registryname)'
  imagename: demopyapp
  login: '$(acrlogin)'
  password: '$(acrpassword)'

steps:
- bash: docker build -f $(system.defaultWorkingDirectory)/Dockerfile -t $(acrurl)/$(imageName):$(build.buildId) $(system.defaultWorkingDirectory)
  displayName: 'docker build'

- bash: |
    docker login $(acrurl) -u $(Login) -p $(password)
    docker push $(acrurl)/$(imageName):$(build.buildId)
  displayName: 'docker push'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'aks'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'